# Default values for oc-python-template.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Empty by default, use envs/<env>/values.yaml for specific configurations.

global:
  applicationName: { { cookiecutter.applicationName } }

k8s-service:
  applicationName: { { cookiecutter.applicationName } }
  containerImage:
    # Organizational mapping prefixes. The repository name is dynamically
    # injected by ArgoCD ApplicationSets (passing the github repo name)
    registry: 485646919618.dkr.ecr.us-east-1.amazonaws.com
    orgId: "{{ cookiecutter.orgId }}"
    buId: "{{ cookiecutter.buId }}"
    appId: "{{ cookiecutter.appId }}"
    repository: ""
